#!/bin/bash
python3 export_onnx.py --cfg_path  ./config/nanodet-m-pose_vit.yml  --model_path ./workspace/nanodet_m_pose_Adam_vit/model_best/model_best.ckpt  --input_shape 320,320 --out_path ./mine_model/masike_nanodet_vit.onnx

python3 -m onnxsim ./mine_model/masike_nanodet_vit.onnx  ./mine_model/masike_nanodet_vit_sim.onnx  
