#!/bin/bash
cd /app/home/muxulong/software/toolChain--/x86/ncnn-20210720_std/build-x86/tools/onnx/
./onnx2ncnn /app/home/muxulong/code/nanodet-main/mine_model/nanodet-sim_0.25x_V20211116A.onnx /app/home/muxulong/code/nanodet-main/mine_model/V20211116A_nanodet.param   /app/home/muxulong/code/nanodet-main/mine_model/V20211116A_nanodet.bin